[build]
builder = "nixpacks"
buildCommand = "npm run build:production"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production" 